#!/bin/bash
# Pre-start script for AIXCL in dev container
# Fixes Docker-in-Docker single file mount issues by copying entrypoints to container filesystem

set -e

echo "=========================================="
echo "AIXCL Pre-Start Setup"
echo "=========================================="

# Create a directory in the container's filesystem (not a mount)
AIXCL_FIX_DIR="/tmp/aixcl-entrypoints"
mkdir -p "$AIXCL_FIX_DIR"

# Copy entrypoint scripts from the mounted location to container filesystem
# This avoids the Docker-in-Docker single file bind mount issue
if [ -d /scripts/runtime ]; then
    echo "Copying entrypoint scripts to $AIXCL_FIX_DIR..."
    cp -v /scripts/runtime/*-entrypoint.sh "$AIXCL_FIX_DIR/" 2>/dev/null || true
    chmod +x "$AIXCL_FIX_DIR"/*-entrypoint.sh 2>/dev/null || true
fi

# Also copy from workspace if they exist there
if [ -d /workspace/scripts/runtime ]; then
    echo "Copying entrypoint scripts from workspace..."
    cp -v /workspace/scripts/runtime/*-entrypoint.sh "$AIXCL_FIX_DIR/" 2>/dev/null || true
    chmod +x "$AIXCL_FIX_DIR"/*-entrypoint.sh 2>/dev/null || true
fi

echo "Entrypoint scripts copied:"
ls -la "$AIXCL_FIX_DIR/"

# Create a docker-compose override file that uses the container-internal paths
# instead of bind-mounted paths
cat > "$AIXCL_FIX_DIR/docker-compose.dev-fix.yml" << 'EOF'
# Docker-in-Docker fix: Use container-internal paths for entrypoints
# This file is auto-generated by the dev container pre-start script

services:
  ollama:
    volumes:
      - /tmp/aixcl-entrypoints/ollama-entrypoint.sh:/ollama-entrypoint.sh:ro
  vllm:
    volumes:
      - /tmp/aixcl-entrypoints/vllm-entrypoint.sh:/vllm-entrypoint.sh:ro
  llamacpp:
    volumes:
      - /tmp/aixcl-entrypoints/llamacpp-entrypoint.sh:/llamacpp-entrypoint.sh:ro
  openwebui:
    volumes:
      - /tmp/aixcl-entrypoints/openwebui-entrypoint.sh:/openwebui-entrypoint.sh:ro
  pgadmin:
    volumes:
      - /tmp/aixcl-entrypoints/pgadmin-entrypoint.sh:/pgadmin-entrypoint.sh:ro
  alloy:
    volumes:
      - /tmp/aixcl-entrypoints/alloy-entrypoint.sh:/alloy-entrypoint.sh:ro
EOF

echo ""
echo "Docker Compose fix file created at:"
echo "  $AIXCL_FIX_DIR/docker-compose.dev-fix.yml"
echo ""
echo "=========================================="
echo "Pre-start complete!"
echo ""
echo "IMPORTANT: When starting AIXCL in dev container, use:"
echo "  export COMPOSE_FILE=services/docker-compose.yml:$AIXCL_FIX_DIR/docker-compose.dev-fix.yml"
echo "  ./aixcl stack start --profile usr"
echo ""
echo "Or set COMPOSE_FILE in your .env file"
echo "=========================================="
