name: Check Environment
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@4.3.0

      - name: Make aixcl executable
        run: chmod +x ./aixcl

      - name: Run aixcl check-env
        run: ./aixcl utils check-env
